version: '2'
services:
  nginx:
    image: nginx:1.17.0
    container_name: "laravel-nginx"
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php

  php:
    build: ./
    expose:
      - "9000"
    volumes:
      - ./src:/src
      - ./php-conf:/etc/php/7.3/fpm/

  mysql:
    image: mysql:8.0
    container_name: "laravel-mysql"
    restart: always
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 13306:3306
