version: '2'
services:
  nginx:
    image: nginx:1.17.0
    container_name: "laravel-nginx"
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./php-fpm-run:/var/run/php
      - ./laravel-product:/var/www/html/project
    depends_on:
      - php

  php:
    build: ./
    container_name: "laravel-php"
    tty: true
    volumes:
      - ./php-conf/php.ini:/etc/php/7.3/fpm/php.ini
      - ./php-fpm-run:/var/run/php
      - ./php-pool/www.conf:/etc/php/7.3/fpm/pool.d/www.conf

  mysql:
    image: mysql:8.0
    container_name: "laravel-mysql"
    restart: always
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 13306:3306
