version: '2'
services:
  nginx:
    image: nginx:1.17.0
    container_name: "laravel-nginx"
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - laravel-public:/var/www/html/project/public
    depends_on:
      - php

  php:
    build: ./
    command: php artisan serve --host 0.0.0.0
    container_name: "laravel-php"
    ports:
      - "8000:8000"
    volumes:
      - ./php-conf/php.ini:/etc/php/7.3/fpm/php.ini
      - laravel-public:/var/www/html/project/public

  mysql:
    image: mysql:8.0
    container_name: "laravel-mysql"
    restart: always
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 13306:3306

volumes:
  laravel-public:
    driver: "local"